#!/bin/sh

set -e
trap '[ $? -eq 0 ] && exit 0 || echo "$0 FAILED"' EXIT

poetry update
poetry export -f requirements.txt -o requirements.txt --without-hashes
sed -i '/extra-index-url/d' requirements.txt
sed -i '/^$/d' requirements.txt

poetry export --dev -f requirements.txt -o requirements-dev.txt --without-hashes
sed -i '/extra-index-url/d' requirements-dev.txt
sed -i '/^$/d' requirements-dev.txt
poetry run dephell convert
git add setup.py poetry.lock requirements.txt requirements-dev.txt

poetry run pylint musicbot tests

kernel=`uname -r`
case "$kernel" in
*microsoft*) echo "No unit testing because docker not available" ;;
*       )
    echo "Running unit tests"
    poetry run pytest --testmon
    poetry run coverage-badge -f -o doc/coverage.svg
    git add doc/coverage.svg
    ;;
esac

poetry run rst-lint doc/help.rst
poetry run doc/gen.sh
poetry run rst-lint README.rst
git add README.rst

exit 0
