FROM debian:sid

RUN apt-get update && apt-get upgrade -y && apt-get install -y libtag1-dev postgresql-server-dev-all python3-pip

WORKDIR /musicbot
ADD setup.py ./
ADD musicbot ./musicbot
RUN python3 setup.py install

RUN mkdir -p ~/.local/share/python_keyring
RUN echo $'[backend] \n\
default-keyring=keyrings.alt.file.PlaintextKeyring' > ~/.local/share/python_keyring/keyringrc.cfg

ENTRYPOINT ["musicbot"]
