FROM node:lts-alpine as build-stage
WORKDIR /musicbot
COPY ui/package*.json ./
RUN npm install
COPY ui .
RUN npm run build

FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /musicbot/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
