#!/usr/bin/env python
# -*- coding: utf-8 -*-

import click
import os
from attrdict import AttrDict
from lib import helpers, config

if os.path.islink(__file__):
    myself = os.readlink(__file__)
else:
    myself = __file__
bin_folder = os.path.dirname(myself)
plugin_folder = os.path.join(bin_folder, 'commands')
CONTEXT_SETTINGS = {'auto_envvar_prefix': 'MUSICBOT', 'help_option_names': ['-h', '--help']}


class SubCommandLineInterface(click.MultiCommand):
    def list_commands(self, ctx):
        rv = []
        for filename in os.listdir(plugin_folder):
            if filename.endswith('.py'):
                rv.append(filename[:-3])
        rv.sort()
        return rv

    def get_command(self, ctx, name):
        ns = {}
        fn = os.path.join(plugin_folder, name + '.py')
        try:
            with open(fn) as f:
                code = compile(f.read(), fn, 'exec')
                eval(code, ns, ns)
        except FileNotFoundError:
            print(ctx.get_help())
            return
        return ns['cli']


@click.command(cls=SubCommandLineInterface, context_settings=CONTEXT_SETTINGS)
@click.version_option("1.0")
@helpers.add_options(config.options)
@click.pass_context
def cli(ctx, **kwargs):
    """Music swiss knife, new gen."""
    ctx.obj = AttrDict
    ctx.obj.folder = bin_folder
    config.config.set(**kwargs)


if __name__ == '__main__':
    cli()
