
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='musicbot',
    version='0.1.0',
    description='Music swiss army knife',
    python_requires='==3.*,>=3.7.0',
    author='Adrien Pensart',
    author_email='crunchengine@gmail.com',
    license='MIT',
    entry_points={'console_scripts': ['musicbot = musicbot.cli:main']},
    packages=['musicbot', 'musicbot.backend', 'musicbot.commands', 'musicbot.music'],
    package_data={'musicbot': ['schema/*.sql']},
    install_requires=['attrdict==2.*,>=2.0.0', 'attrs==19.*,>=19.1.0', 'click==7.*,>=7.0.0', 'click-aliases==1.*,>=1.0.1', 'click-didyoumean==0.*,>=0.0.3', 'click-man==0.*,>=0.3.0', 'click-spinner==0.*,>=0.1.8', 'coloredlogs==10.*,>=10.0.0', 'feedparser==5.*,>=5.2.1', 'graphql-py==0.*,>=0.7.1', 'humanfriendly==4.*,>=4.18.0', 'isodate==0.*,>=0.6.0', 'isort[pyproject]==4.*,>=4.3.0', 'logging-tree==1.*,>=1.8.0', 'pgcli==2.*,>=2.1.1', 'psycopg2-binary==2.*,>=2.8.0', 'pyacoustid==1.*,>=1.1.0', 'pydub==0.*,>=0.23.1', 'pytaglib==1.*,>=1.4.0', 'python-vlc==3.*,>=3.0.0', 'pytube==9.*,>=9.4.0', 'spotipy==2.*,>=2.4.0', 'tqdm==4.*,>=4.31.0', 'watchdog==0.*,>=0.9.0'],
    extras_require={'dev': ['coverage-badge==1.*,>=1.0.0', 'pylint==2.*,>=2.3.0', 'pytest==5.*,>=5.2.4', 'pytest-click==0.*,>=0.3.0', 'pytest-cov==2.*,>=2.6.0', 'pytest-docker-compose==3.*,>=3.1.2', 'pytest-xdist==1.*,>=1.28.0']},
)
