# AUTOGENERATED FROM 'musicbot/queries/drop_schema.edgeql' WITH:
#     $ gel-py --dir musicbot/queries -I musicbot-prod


from __future__ import annotations

import gel


async def drop_schema(
    executor: gel.AsyncIOExecutor,
) -> None:
    await executor.execute(
        """\
        reset schema to initial;\
        """,
    )
