# AUTOGENERATED FROM 'musicbot/queries/drop_schema.edgeql' WITH:
#     $ edgedb-py -I musicbot-prod --dir musicbot/queries


from __future__ import annotations

import edgedb


async def drop_schema(
    executor: edgedb.AsyncIOExecutor,
) -> None:
    await executor.execute(
        """\
        reset schema to initial;\
        """,
    )
