# AUTOGENERATED FROM 'musicbot/queries/gen_bests.edgeql' WITH:
#     $ gel-py --dir musicbot/queries -I musicbot-test


from __future__ import annotations

import gel

Length = int
Limit = int
Rating = float
Size = int


async def gen_bests(
    executor: gel.AsyncIOExecutor,
    *,
    min_length: Length,
    max_length: Length,
    min_size: Size,
    max_size: Size,
    min_rating: Rating,
    max_rating: Rating,
    artist: str,
    album: str,
    genre: str,
    title: str,
    keyword: str,
    pattern: str,
    limit: Limit,
) -> str:
    return await executor.query_single(
        """\
        select gen_bests(
            min_length := <Length>$min_length,
            max_length := <Length>$max_length,
            min_size := <Size>$min_size,
            max_size := <Size>$max_size,
            min_rating := <Rating>$min_rating,
            max_rating := <Rating>$max_rating,
            artist := <str>$artist,
            album := <str>$album,
            genre := <str>$genre,
            title := <str>$title,
            keyword := <str>$keyword,
            pattern := <str>$pattern,
            `limit` := <`Limit`>$limit,
        )\
        """,
        min_length=min_length,
        max_length=max_length,
        min_size=min_size,
        max_size=max_size,
        min_rating=min_rating,
        max_rating=max_rating,
        artist=artist,
        album=album,
        genre=genre,
        title=title,
        keyword=keyword,
        pattern=pattern,
        limit=limit,
    )
