# AUTOGENERATED FROM 'musicbot/queries/pike_keywords.edgeql' WITH:
#     $ edgedb-py -I musicbot-prod --dir musicbot/queries


from __future__ import annotations

import edgedb


async def pike_keywords(
    executor: edgedb.AsyncIOExecutor,
) -> list[str]:
    return await executor.query(
        """\
        for keyword in (
            select Keyword {name}
            filter contains(array_agg(.musics.keywords.name), 'pike') and .musics.rating >= 4.0 and .musics.album.artist.name = 'Buckethead'
        )
        union (keyword.name) except {'pike'}\
        """,
    )
