# AUTOGENERATED FROM 'musicbot/queries/upsert_keyword.edgeql' WITH:
#     $ gel-py --dir musicbot/queries -I musicbot-test


from __future__ import annotations

import uuid

import gel


async def upsert_keyword(
    executor: gel.AsyncIOExecutor,
    *,
    keyword: str,
) -> uuid.UUID:
    return await executor.query_single(
        """\
        select upsert_keyword(
            keyword := <str>$keyword
        ).id\
        """,
        keyword=keyword,
    )
