# AUTOGENERATED FROM 'musicbot/queries/upsert_genre.edgeql' WITH:
#     $ gel-py --dir musicbot/queries -I musicbot-test


from __future__ import annotations

import uuid

import gel


async def upsert_genre(
    executor: gel.AsyncIOExecutor,
    *,
    genre: str,
) -> uuid.UUID:
    return await executor.query_single(
        """\
        select upsert_genre(
            genre := <str>$genre
        ).id\
        """,
        genre=genre,
    )
