# AUTOGENERATED FROM 'musicbot/queries/upsert_folder.edgeql' WITH:
#     $ gel-py --dir musicbot/queries -I musicbot-test


from __future__ import annotations

import uuid

import gel


async def upsert_folder(
    executor: gel.AsyncIOExecutor,
    *,
    folder: str,
    username: str,
    ipv4: str,
) -> uuid.UUID:
    return await executor.query_single(
        """\
        select upsert_folder(
            folder := <str>$folder,
            username := <str>$username,
            ipv4 := <str>$ipv4
        ).id\
        """,
        folder=folder,
        username=username,
        ipv4=ipv4,
    )
