# AUTOGENERATED FROM 'musicbot/queries/upsert_artist.edgeql' WITH:
#     $ gel-py --dir musicbot/queries -I musicbot-test


from __future__ import annotations

import uuid

import gel


async def upsert_artist(
    executor: gel.AsyncIOExecutor,
    *,
    artist: str,
) -> uuid.UUID:
    return await executor.query_single(
        """\
        select upsert_artist(
            artist := <str>$artist
        ).id\
        """,
        artist=artist,
    )
