# AUTOGENERATED FROM 'musicbot/queries/upsert_album.edgeql' WITH:
#     $ gel-py --dir musicbot/queries -I musicbot-test


from __future__ import annotations

import uuid

import gel


async def upsert_album(
    executor: gel.AsyncIOExecutor,
    *,
    artist: uuid.UUID,
    album: str,
) -> uuid.UUID:
    return await executor.query_single(
        """\
        select upsert_album(
            artist := <Artist>$artist,
            album := <str>$album
        ).id\
        """,
        artist=artist,
        album=album,
    )
