---
name: Python application
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libtag1-dev postgresql-server-dev-all ffmpeg
          pip install -r requirements-dev.txt
      - name: Lint with pylint
        run: |
          pip install pylint
          pylint musicbot tests
      - name: Test with pytest
        env:
          MB_SPOTIFY_CACHE: ${{ secrets.MB_SPOTIFY_CACHE }}
          MB_SPOTIFY_CLIENT_ID: ${{ secrets.MB_SPOTIFY_CLIENT_ID }}
          MB_SPOTIFY_CLIENT_SECRET: ${{ secrets.MB_SPOTIFY_CLIENT_SECRET }}
        run: |
          echo "$env:MB_SPOTIFY_CACHE" > .spotify_cache
          pytest
