---
name: Python application
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libtag1-dev postgresql-server-dev-all ffmpeg vlc
          pip install -r requirements-dev.txt
      - name: Linting
        run: |
          pylint musicbot tests
          rst-lint README.rst
      - name: Test with pytest
        env:
          MB_SPOTIFY_CACHE: ${{ secrets.MB_SPOTIFY_CACHE }}
          MB_SPOTIFY_CLIENT_ID: ${{ secrets.MB_SPOTIFY_CLIENT_ID }}
          MB_SPOTIFY_CLIENT_SECRET: ${{ secrets.MB_SPOTIFY_CLIENT_SECRET }}
        run: |
          echo -n "$MB_SPOTIFY_CACHE" > $HOME/.spotify_cache
          MB_SPOTIFY_CACHE_PATH=$HOME/.spotify_cache pytest
      - name: Build package
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
        run: |
          python3 setup.py bdist_wheel sdist
      - name: Publish package
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
